[[deb]]
=== 使用 Debian 包安装 Elasticsearch

Debian 包可以从 <<install-deb,从官网下载>> 或者 <<deb-repo,APT 仓库>>获取。
它适用于 Debian 和 Ubuntu 等所有 Debian-based 系统。

最新的稳定版本可以在
link:/downloads/elasticsearch[Download Elasticsearch] 找到。
其他版本可以在
link:/downloads/past-releases[Past Releases page]找到。

NOTE: Elasticsearch 最低要求 Java 8。使用
http://www.oracle.com/technetwork/java/javase/downloads/index.html[official Oracle distribution]
或者开源版本 http://openjdk.java.net[OpenJDK]。

[[deb-key]]
==== 引入 Elasticsearch PGP Key

include::key.asciidoc[]

[source,sh]
-------------------------
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
-------------------------

[[deb-repo]]
==== 从 APT 仓库安装

ifeval::["{release-state}"=="unreleased"]

Elasticsearch Version {version} 暂未发布。

endif::[]

ifeval::["{release-state}"!="unreleased"]

运行之前你需要在 Debian 安装 `apt-transport-https` 包。

[source,sh]
--------------------------------------------------
sudo apt-get install apt-transport-https
--------------------------------------------------

将仓库定义保存到  +/etc/apt/sources.list.d/elastic-{major-version}.list+:

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/{major-version}/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/{major-version}-prerelease/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]


[NOTE]
==================================================

不适用 `add-apt-repository` 有以下原因：


. `add-apt-repository` 将 entries 添加到系统 `/etc/apt/sources.list` 文件，
  而不是`/etc/apt/sources.list.d` 中干净的 per-repository 文件。
. `add-apt-repository` 在很多版本上不是默认安装的并且需要很多非默认依赖。
. 旧版本的 `add-apt-repository` 经常添加一个 `deb-src` entry，这会造成错误，因为我们不提供源代码包。如果你添加 `deb-src` entry，除非删除 `deb-src` 否则你会看到以下错误：


    Unable to find expected entry 'main/source/Sources' in Release file
    (Wrong sources.list entry or malformed file)

==================================================

你可以用 Debian 包安装 Elasticsearch：

[source,sh]
--------------------------------------------------
sudo apt-get update && sudo apt-get install elasticsearch
--------------------------------------------------

[WARNING]
==================================================
如果同一个 Elasticsearch 库中存在两个 entries，则在 `apt-get update` 中会看到类似这样的错误：

["literal",subs="attributes,callouts"]

Duplicate sources.list entry https://artifacts.elastic.co/packages/{major-version}/apt/ ...`

检查 +/etc/apt/sources.list.d/elasticsearch-{major-version}.list+ 或者从 `/etc/apt/sources.list.d/` 和 `/etc/apt/sources.list` 文件中定位重复 entry。
==================================================

endif::[]

include::skip-set-kernel-parameters.asciidoc[]

[[install-deb]]
==== 手动下载安装 Debian 包

ifeval::["{release-state}"=="unreleased"]

Elasticsearch Version {version} 暂未发布。

endif::[]

ifeval::["{release-state}"!="unreleased"]

Elasticsearch v{version} Debian 包可从官网下载安装：

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{version}.deb
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{version}.deb.sha512
shasum -a 512 -c elasticsearch-{version}.deb.sha512 <1>
sudo dpkg -i elasticsearch-{version}.deb
--------------------------------------------
<1> 比较下载的 Debian 包的 SHA 和 发布校验和，应该输出
        `elasticsearch-{version}.zip: OK`。

endif::[]

include::init-systemd.asciidoc[]

[[deb-running-init]]
==== SysV `init` 运行 Elasticsearch

系统启动时可使用 `update-rc.d` 命令手动配置启动 Elasticsearch：

[source,sh]
--------------------------------------------------
sudo update-rc.d elasticsearch defaults 95 10
--------------------------------------------------

可以用 `service` 命令启动和停止 Elasticsearch：

[source,sh]
--------------------------------------------
sudo -i service elasticsearch start
sudo -i service elasticsearch stop
--------------------------------------------

如果启动失败，Elasticsearch 会将错误日志打印输出。具体日志可以在 `/var/log/elasticsearch/` 找到。

[[deb-running-systemd]]
include::systemd.asciidoc[]

[[deb-check-running]]
include::check-running.asciidoc[]

[[deb-configuring]]
==== 配置 Elasticsearch

include::etc-elasticsearch.asciidoc[]

Debian package 同样有一个系统配置文件 (`/etc/default/elasticsearch`)，该文件允许你设置如下参数：

include::sysconfig-file.asciidoc[]

NOTE: `systemd` 版本要求资源通过 `systemd` 配置而不是 `/etc/sysconfig/elasticsearch` 文件。
更多详情请参考 <<systemd>>。

[[deb-layout]]
==== Debian 包目录结构

Debian 包将配置文件、日志和数据目录放在 Debian 系统合适位置：


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | Elasticsearch 根目录或 `$ES_HOME`
  | /usr/share/elasticsearch
 d|

| bin
  | 二进制脚本，包括启动节点的 `elasticsearch` 和安装插件的
     `elasticsearch-plugin`
  | /usr/share/elasticsearch/bin
 d|

| conf
  | 包含 `elasticsearch.yml` 的配置文件
  | /etc/elasticsearch
  | <<config-files-location,ES_PATH_CONF>>

| conf
  | 包含堆大小，文件描述符的环境变量。
  | /etc/default/elasticsearch
 d|

| data
  | 每个节点分配的 index / shard 数据文件。支持多路径。
  | /var/lib/elasticsearch
  | path.data

| logs
  | Log 文件路径。
  | /var/log/elasticsearch
  | path.logs

| plugins
  | Plugin 文件路径。每个插件都包含在一个子目录中。
  | /usr/share/elasticsearch/plugins
  |

| repo
  | 共享文件系统库路径。支持多路径。一个文件系统库可以在此处指定的任何目录的任何子目录中。
 d| 未配置
  | path.repo

|=======================================================================

include::next-steps.asciidoc[]
