[[rpm]]
=== 使用 RPM 安装 Elasticsearch

RPM 包可以从 <<install-rpm,从官网下载>> 或者 <<rpm-repo,RPM 仓库>>获取。
它适用于 OpenSuSE、SLES、Centos、Red Hat 和 Oracle Enterprise 等所有 RPM-based 系统。

NOTE: 不支持 SLES 11 和 CentOS 5 等老版本的 RPM 安装。请使用 <<zip-targz>> 替换。

最新的稳定版本可以在
link:/downloads/elasticsearch[Download Elasticsearch] 找到。
其他版本可以在
link:/downloads/past-releases[Past Releases page]找到。

NOTE: Elasticsearch 最低要求 Java 8。使用
http://www.oracle.com/technetwork/java/javase/downloads/index.html[official Oracle distribution]
或者开源版本 http://openjdk.java.net[OpenJDK]。

[[rpm-key]]
==== 引入 Elasticsearch PGP Key

include::key.asciidoc[]

[source,sh]
-------------------------
rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
-------------------------

[[rpm-repo]]
==== 从 RPM 仓库安装

ifeval::["{release-state}"=="unreleased"]

Elasticsearch Version {version} 暂未发布。

endif::[]

ifeval::["{release-state}"!="unreleased"]

在 RedHat `/etc/yum.repos.d/` 或 OpenSuSE `/etc/zypp/repos.d/` 目录创建 `elasticsearch.repo` 文件，包括：

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
[elasticsearch-{major-version}]
name=Elasticsearch repository for {major-version} packages
baseurl=https://artifacts.elastic.co/packages/{major-version}/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
--------------------------------------------------

endif::[]

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
[elasticsearch-{major-version}]
name=Elasticsearch repository for {major-version} packages
baseurl=https://artifacts.elastic.co/packages/{major-version}-prerelease/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
--------------------------------------------------

endif::[]

当仓库可用时，你可用使用以下命令之一安装 Elasticsearch：

[source,sh]
--------------------------------------------------
sudo yum install elasticsearch <1>
sudo dnf install elasticsearch <2>
sudo zypper install elasticsearch <3>
--------------------------------------------------
<1> 在 CentOS 或老版本 Red Hat 执行 `yum`。
<2> 在 Fedora 或新版本 Red Hat 执行 `dnf`。
<3> 在 OpenSUSE 版本执行 `zypper`。

endif::[]

[[install-rpm]]
==== 手动下载安装 RPM

ifeval::["{release-state}"=="unreleased"]

Elasticsearch Version {version} 暂未发布。

endif::[]

ifeval::["{release-state}"!="unreleased"]

Elasticsearch v{version} RPM 包可从官网下载安装：

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{version}.rpm
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{version}.rpm.sha512
shasum -a 512 -c elasticsearch-{version}.rpm.sha512 <1>
sudo rpm --install elasticsearch-{version}.rpm
--------------------------------------------
<1> 比较下载的 RPM 的 SHA 和 发布校验和，应该输出
        `elasticsearch-{version}.zip: OK`。

endif::[]

include::skip-set-kernel-parameters.asciidoc[]

include::init-systemd.asciidoc[]

[[rpm-running-init]]
==== SysV `init` 运行 Elasticsearch

当系统启动时可使 `chkconfig` 命令手动配置启动 Elasticsearch：

[source,sh]
--------------------------------------------------
sudo chkconfig --add elasticsearch
--------------------------------------------------

可以用 `service` 命令启动和停止 Elasticsearch：

[source,sh]
--------------------------------------------
sudo -i service elasticsearch start
sudo -i service elasticsearch stop
--------------------------------------------

如果启动失败，Elasticsearch 会将错误日志打印输出。具体日志可以在 `/var/log/elasticsearch/` 找到。


[[rpm-running-systemd]]
include::systemd.asciidoc[]

[[rpm-check-running]]
include::check-running.asciidoc[]

[[rpm-configuring]]
==== 配置 Elasticsearch

include::etc-elasticsearch.asciidoc[]

RPM 同样有一个系统配置文件 (`/etc/default/elasticsearch`)，该文件允许你设置如下参数：

include::sysconfig-file.asciidoc[]

NOTE: `systemd` 版本要求资源通过 `systemd` 配置而不是 `/etc/sysconfig/elasticsearch` 文件。
更多详情请参考 <<systemd>>。


[[rpm-layout]]
==== RPM 包目录结构

RPM 将配置文件、日志和数据目录放在 RPM 系统合适位置：


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | Elasticsearch 根目录或 `$ES_HOME`
  | /usr/share/elasticsearch
 d|

| bin
  | 二进制脚本，包括启动节点的 `elasticsearch` 和安装插件的
     `elasticsearch-plugin`
  | /usr/share/elasticsearch/bin
 d|

| conf
  | 包含 `elasticsearch.yml` 的配置文件
  | /etc/elasticsearch
  | <<config-files-location,ES_PATH_CONF>>

| conf
  | 包含堆大小，文件描述符的环境变量。
  | /etc/sysconfig/elasticsearch
 d|

| data
  | 每个节点分配的 index / shard 数据文件。支持多路径。
  | /var/lib/elasticsearch
  | path.data

| logs
  | Log 文件路径。
  | /var/log/elasticsearch
  | path.logs

| plugins
  | Plugin 文件路径。每个插件都包含在一个子目录中。
  | /usr/share/elasticsearch/plugins
  |

| repo
  | 共享文件系统库路径。支持多路径。一个文件系统库可以在此处指定的任何目录的任何子目录中。
 d| 未配置
  | path.repo

|=======================================================================

include::next-steps.asciidoc[]
