[[settings]]
== 配置 Elasticsearch

Elasticsearch 具有良好的默认配置，同时只需少量配置。
大多数设置可在集群运行时使用
<<cluster-update-settings>> API 更改。

配置文件应该包含节点特定（例如 `node.name` 和路径）设置，或者节点加入集群而需要的设置，例如 `cluster.name` 和 `network.host` 。

[[config-files-location]]
[float]
=== 配置文件路径

Elasticsearch 有三个配置文件：

* `elasticsearch.yml` 用于配置 Elasticsearch
* `jvm.options` 用于配置 Elasticsearch JVM 设置
* `log4j2.properties` 用于配置 Elasticsearch 日志

这些文件存在于 config 目录，默认路径取决于安装来源是归档版本（`tar.gz` 或者
`zip` ）还是包版本（Debian 或 RPM 包）。

对于归档版本，config 目录位于 `$ES_HOME/config` 。config 目录路径可以通过 `ES_PATH_CONF` 环境变量改变：

[source,sh]
-------------------------------
ES_PATH_CONF=/path/to/my/config ./bin/elasticsearch
-------------------------------

你可以通过命令行或 shell 配置 `export` `ES_PATH_CONF` 环境变量。

对于包版本，config 默认目录位置为 `/etc/elasticsearch` 。 可以通过 `ES_PATH_CONF` 环境变量更改 config 目录位置，但请注意，仅仅在 shell 中设置不够的。 相反，这个变量来源于
`/etc/default/elasticsearch` （Debian 包）和
`/etc/sysconfig/elasticsearch` （RPM 包）。
你需要编辑位于这些文件的 `ES_PATH_CONF=/etc/elasticsearch` 项来更改 config 目录位置。


[float]
=== 配置文件格式

配置格式是 http://www.yaml.org/[YAML] 。 以下是一个更改数据和日志目录路径的示例：

[source,yaml]
--------------------------------------------------
path:
    data: /var/lib/elasticsearch
    logs: /var/log/elasticsearch
--------------------------------------------------

可用如下方式展开设置：

[source,yaml]
--------------------------------------------------
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
--------------------------------------------------

[float]
=== 替换环境变量

配置文件内用 `${...}` 符号引用的环境变量将被替换为环境变量值，例如：

[source,yaml]
--------------------------------------------------
node.name:    ${HOSTNAME}
network.host: ${ES_NETWORK_HOST}
--------------------------------------------------

[float]
=== 提示设置

如果不希望将设置存储在配置文件中，你可以使用 `${prompt.text}` 或 `${prompt.secret}` 值并在前台启动 Elasticsearch。
`${prompt.secret}` 禁用回显所以输入的值不会显示在终端；`${prompt.text}` 允许你在输入时查看该值。例如：

[source,yaml]
--------------------------------------------------
node:
  name: ${prompt.text}
--------------------------------------------------

启动 Elasticsearch 时，系统会提示你像这样输入实际值：

[source,sh]
--------------------------------------------------
Enter value for [node.name]:
--------------------------------------------------

NOTE: 如果在设置中使用了 `${prompt.text}` 或 `${prompt.secret}` ，同时该进程作为后台服务运行，则无法启动 Elasticsearch。
