[[stopping-elasticsearch]]
== 停止 Elasticsearch

有序关闭 Elasticsearch 保证了 Elasticsearch 有机会清理和关闭突出资源。例如，有序关闭的节点将会自动从集群中移除，
同步事务日志到磁盘，并执行其他相关的清理活动。你可以通过合适地有序关闭来帮助停止 Elasticsearch。

如果你正在以服务运行 Elasticsearch，你可以通过安装时的服务管理功能停止 Elasticsearch。

如果你直接运行 Elasticsearch，可以通过向控制台发送 control-C 停止 Elasticsearch，或在 POSIX 系统上向 Elasticsearch 进程发送 `SIGTERM`。
可以通过多种工具（例如 `ps` 或 `jps`）获得用于发送信号的 PID ：

[source,sh]
--------------------------------------------------
$ jps | grep Elasticsearch
14542 Elasticsearch
--------------------------------------------------

Elasticsearch 启动日志：

[source,sh]
--------------------------------------------------
[2016-07-07 12:26:18,908][INFO ][node                     ] [I8hydUG] version[5.0.0-alpha4], pid[15399], build[3f5b994/2016-06-27T16:23:46.861Z], OS[Mac OS X/10.11.5/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_92/25.92-b14]
--------------------------------------------------

或者通过在启动时指定写入 PID 文件位置（`-p <path>`）：

[source,sh]
--------------------------------------------------
$ ./bin/elasticsearch -p /tmp/elasticsearch-pid -d
$ cat /tmp/elasticsearch-pid && echo
15516
$ kill -SIGTERM 15516
--------------------------------------------------

[[fatal-errors]
[float]
=== 致命错误停止

在 Elasticsearch 虚拟机的生命周期中，可能会出现一些致命错误导致虚拟机处在一个错误状态。这种致命错误包括内存错误、虚拟机内部错误和严重 I/O 错误。

当 Elasticsearch 发现虚拟机遇到上述致命错误时将尝试记录这些日志并关闭虚拟机。
当 Elasticsearch 发起这种关闭时，不会像上面所描述的那样有序关闭。
Elasticsearch 进程同样将返回一个指示错误性质的特殊状态码。

[horizontal]
JVM internal error:: 128
Out of memory error:: 127
Stack overflow error:: 126
Unknown virtual machine error:: 125
Serious I/O error:: 124
Unknown fatal error:: 1
