[[breaking_60_indices_changes]]
=== Indices 改变

==== 索引模板使用 `index_patterns` 替换 `template`

早期使用模板表示索引时需要在 `template` 字段中匹配 glob 类型模式。现在应该使用 `index_patterns` 字段替换。
正如名称暗示的一样你可以在数组中定义多个 glob 类型模式，但是为了方便支持使用单字符串定义一个模式。所以以下两个实例都是有效的：

[source,js]
--------------------------------------------------
PUT _template/template_1
{
  "index_patterns": ["te*", "bar*"],
  "settings": {
    "number_of_shards": 1
  }
}
PUT _template/template_2
{
  "index_patterns": "te*",
  "settings": {
    "number_of_shards": 1
  }
}
--------------------------------------------------
// CONSOLE


==== 移除影子副本

影子副本没有发现足够使用场景，并且已被删除。这包括以下设置：

- `index.shared_filesystem`
- `index.shadow_replicas`
- `node.add_lock_id_to_custom_path`

==== 打开/关闭 索引 API 默认允许未匹配索引通配符表达式

打开/关闭 索引 API 中的 `allow_no_indices` 选项默认值由 `false` 改为 `true` ，使其与删除索引 API 行为对齐。
这样做的结果是 打开/关闭 索引 API 在通配符表达式未匹配到任何 关闭/打开 索引时默认返回 error。

==== 删除文档

从不存在的索引中删除文档已被修改为不创建索引。但是，如果使用外部版本则会创建索引，同时文档
将被标记为删除。

==== 索引别名 api 仅针对索引解析索引表达式

update-aliases、put-alias 和 delete-alias APIs 中的索引参数不再接收别名名称。相反，它只接收索引名称（或衍生至匹配索引的通配符）。

==== 删除索引 api 仅针对索引解析索引表达式

删除索引 API 中的索引参数不再支持别名名称。相反，它只接收索引名称（或衍生至匹配索引的通配符）。

==== 索引表达式不再支持 `+`

省略 `+` 与指定它的效果相同，因此索引表达式不再支持 `+` 。

==== 保留事务日志

事务日志文件最长保留 12 小时（默认），最大保留大小为 `512mb` （默认），并且 `flush` 时不再删除。
这是为了执行恢复操作时提高复制速度。

==== 限制 NGramTokenFilter 和 NGramTokenizer 中 max_size 和 min_size 之间的差异

为了防止创建太多的索引词项，NGramTokenFilter 和 NGramTokenizer 中的 max_ngram 和 min_ngram 之间的差异限制为 1。
这个默认限制可以通过索引设置 index.max_ngram_diff 改变。注意如果超出限制将记录一个过期警告。

==== 限制 ShingleTokenFilter 中 max_size 和 min_size 之间的差异

为了防止创建太多的词元，ShingleTokenFilter 中 max_shingle_size 和 min_shingle_size 之间的差异限制为3。
这个默认限制可以通过索引设置 index.max_shingle_diff 改变。注意如果超出限制将记录一个过期警告。
