[[breaking_60_java_changes]]
=== Java API 改变

==== `setSource` 方法需要 XContentType

早期版本接收表示对象源的 byte/string 的 `setSource` 和其他方法不需要指定 XContentType。
内容类型自动检测已不再使用，因此这些方法在以字节或字符串形式提供 source 时需要指定 XContentType 作为附加参数。

==== `DeleteByQueryRequest` 需要显示设置查询

早期 Elasticsearch 版本，delete by query 请求不需要显示设置 query，match_all 作为默认查询并且所有文档会被删除。
从 6.0.0 版本起，`DeleteByQueryRequest` 需要显示设置 query。

==== 移除 `InternalStats` 和 `Stats` getCountAsString() 方法

stats 聚合中的 `count` 值表示不需要格式化版本的文档数。这个方法在 5.4 中被弃用，在需要时可用 `String.valueOf(getCount())` 支持。

==== `ActionRequestBuilder#execute` 返回 `ActionFuture` 而不是 `ListenableActionFuture`

当通过类似 client.prepareSearch().execute() 构建器发送请求时，过去它可以调用 `addListener` 返回 `ListenableActionFuture` 。
现在替换为与 `Client` 方法返回一致的 `ActionFuture` ，于是与监听器关联起来是不可能的。可以用 `execute` 方法接收监听器作为参数替换。

==== `Terms.Order` 和 `Histogram.Order` 类由 `BucketOrder` 取代

`terms` 、`histogram` 和 `date_histogram` 聚合代码已经被重构为用于排序 buckets 的通用代码。`BucketOrder` 类用于替换 `Terms.Order` 和
`Histogram.Order` 。必须使用 `BucketOrder` 类的 `static` 方法而不是直接访问内部 order 实例，
例如 `BucketOrder.count(boolean)` 和 `BucketOrder.aggregation(String, boolean)` 。使用 `BucketOrder.key(boolean)` 提供 `_term` 的 `terms` 聚合。

==== `BulkResponse` 、 `SearchResponse` 和 `TermVectorsResponse` 移除了 `getTookInMillis()`

为了支持 `getTook` 方法，已经移除了 `BulkResponse` 、 `SearchResponse` 和 `TermVectorsResponse` 中的 `getTookInMiilis()` 方法。
`getTookInMiilis()` 很容易被 `getTook().getMillis()` 替换。

==== `GetField` 和 `SearchHitField` 由 `DocumentField` 取代

因为 `GetField` 和 `SearchHitField` 具有相同的成员，所以它们已经统一成了 `DocumentField` 。

==== 移动了一些聚合类的包

range 聚合（geo_distance 、 date 和 ip）的相关类移动至 `org.elasticsearch.search.aggregations.bucket.range` 包。

`org.elasticsearch.search.aggregations.bucket.terms.support` 包已被移除，包里面的类移动至 `org.elasticsearch.search.aggregations.bucket.terms`。

过滤器聚合类移动至 `org.elasticsearch.search.aggregations.bucket.filter` 。

==== `PercentileRanksAggregationBuilder` 构造器已改变

现在需要将所要求的等级作为非 null 、非空 double 数据传至构建器构造函数中，而不是通过构建器的 setter 配置。setter `values()` 方法也相应的移除了。
