[[breaking_60_settings_changes]]
=== Settings 改变

==== 移除对 elasticsearch.json 和 elasticsearch.yaml 配置文件地支持

早期 Elasticsearch config 目录下有 `.yml` 、 `.yaml` 或 扩展 `.json` 配置文件。现在只支持 `elasticsearch.yml` 。

==== 配置文件重复键

早期 Elasticsearch，配置文件允许包含重复键。例如：

[source,yaml]
--------------------------------------------------
node:
  name: my-node

node
  attr:
    rack: my-rack
--------------------------------------------------

在 Elasticsearch 6.0.0 中，这不再允许。现在必须在一个 key 里面指定：

[source,yaml]
--------------------------------------------------
node:
  name: my-node
  attr:
    rack: my-rack
--------------------------------------------------

==== 强制布尔设置

早期 Elasticsearch 将 `true` 、 `false` 、`on` 、 `off` 、 `yes` 、 `no` 、 `0` 、 `1` 识别为布尔。
Elasticsearch 6.0 中只将 `true` 和 `false` 识别为布尔，其他情况会抛出 error。
为了向前兼容，6.x 系列中上面的强制规则仍将在 pre-6.0 索引上正常工作。注意这不适用于存储在 `elasticsearch.yml` 的节点级设置。

==== 快照设置

允许正在执行快照的分片重分配到不同节点的内部设置 `cluster.routing.allocation.snapshot.relocation_enabled` 已移除。
如果分片从节点分配，启用此设置可能会导致分配问题。
启用该设置可能导致在节点分配的分片在快照运行时被重新分配到该节点。

==== 存储限流设置

存储限流已移除。因此，`indices.store.throttle.type` 和 `indices.store.throttle.max_bytes_per_sec`
集群设置以及 `index.store.throttle.type` 和 `index.store.throttle.max_bytes_per_sec` 索引设置不能再识别。

==== 存储设置

`default` `index.store.type` 已移除。如果你使用它，我们建议从索引设置中简单地移除它，Elasticsearch 将为你的操作系统使用最佳 `store` 实现。

==== 网络设置

阻塞 TCP 客户端，阻塞 TCP 服务端和阻塞 HTTP 服务断已移除。因此， `network.tcp.blocking_server` 、`network.tcp.blocking_client` 、
`network.tcp.blocking` 、`transport.tcp.blocking_client` 、`transport.tcp.blocking_server` 和 `http.tcp.blocking_server` 设置不能再识别。

早期未使用的设置 `transport.netty.max_cumulation_buffer_capacity` 、`transport.netty.max_composite_buffer_components` 和 `http.netty.max_cumulation_buffer_capacity` 已移除。

==== 相似性设置

因为 coords 和查询标准化已移除使得 `base` 相似性现在会被忽略。 如果提供，这个设置会被忽略并会产生一个过期警告。

==== 脚本设置

所以已存在的脚本安全设置已移除。请使用 `script.allowed_types` 和 `script.allowed_contexts` 替代。

==== 发现设置

`discovery.type` 设置不再支持 `gce` 、 `aws` 和 `ec2` 值。
与这些平台整合需要设置 `discovery.zen.hosts_provider` 为这些值中的一个。
