[[setting-system-settings]]
=== 配置系统设置

在何处配置系统设置取决于你之前安装 Elasticsearch 的包类型，以及你正在使用的操作系统类型。

当使用 `.zip` 或 `.tar.gz` 包时，系统设置配置如下：

* 使用 <<ulimit,`ulimit`>> 临时生效， 或者
* <<limits.conf,`/etc/security/limits.conf`>> 永久生效。

当使用 RPM 或 Debian 包时，大多数系统设置都在 <<sysconfig,system 配置文件>> 。
但是使用 systemd 的系统要求在 <<systemd,systemd 配置文件>> 中指定系统限制。

[[ulimit]]
==== `ulimit`

在 Linux 系统上，`ulimit` 可用于临时改变资源。在切换为运行 Elasticsearch 的账号前，通常需要 `root` 权限。
例如，设置打开文件句柄（ `ulimit -n` ）数为 65,536，你可以这样做：

[source,sh]
--------------------------------
sudo su  <1>
ulimit -n 65536 <2>
su elasticsearch <3>
--------------------------------
<1> 切换 `root`.
<2> 改变最大打开文件数。
<3> 切换 `elasticsearch` 账号用于启动 Elasticsearch。

新的 limit 仅适用于当前会话。

您可以使用 `ulimit -a` 查询所有当前应用的 limits。

[[limits.conf]]
==== `/etc/security/limits.conf`

在 Linux 系统上，可以通过编辑 `/etc/security/limits.conf` 文件来为指定用户设置固定 limits。
为了将 `elasticsearch` 账号最大打开文件数设为 65,536，可在 `limits.conf` 文件中添加以下行：


[source,sh]
--------------------------------
elasticsearch  -  nofile  65536
--------------------------------

此更改仅在 `elasticsearch` 账号开启新 session 时生效。

[NOTE]
.Ubuntu 和 `limits.conf`
===============================
Ubuntu 忽略由 `init.d` 启动进程的 `limits.conf` 文件。 为了启用 `limits.conf` 文件，请编辑 `/etc/pam.d/su` 并取消以下行注释：

[source,sh]
--------------------------------
# session    required   pam_limits.so
--------------------------------
===============================

[[sysconfig]]
==== Sysconfig 文件

使用 RPM 或 Debian 包时，系统设置和环境变量可由位于以下路径的系统配置文件指定：

[horizontal]
RPM::     `/etc/sysconfig/elasticsearch`
Debian::  `/etc/default/elasticsearch`

但是，对于使用 `systemd` 的系统，需要通过 <<systemd,systemd>> 指定系统 limits。

[[systemd]]
==== Systemd 配置

当 RPM 或 Debian 包使用 https://en.wikipedia.org/wiki/Systemd[systemd] 时，系统 limits 必须由 systemd 指定。

systemd 服务文件（ `/usr/lib/systemd/system/elasticsearch.service` ）包含默认应用的 limits。

要覆盖它们，请添加一个名为 `/etc/systemd/system/elasticsearch.service.d/override.conf` 的文件（或者，
你可以在你的默认编辑器中运行 `sudo systemctl edit elasticsearch` 来打开文件）。在文件中设置任何更改，例如：

[source,sh]
---------------------------------
[Service]
LimitMEMLOCK=infinity
---------------------------------

一旦完成，运行如下命令重载：

[source,sh]
---------------------------------
sudo systemctl daemon-reload
---------------------------------
