[[setup-configuration-memory]]
=== 禁用 swapping

大多数操作系统尝试让文件系统缓存用尽可能多的内存，并急切地换出未使用的应用内存。
这可能会导致部分 JVM 堆或其可执行页面被交换到磁盘。

Swapping 对性能非常不利，为了节点稳定应该不惜一切代价避免 Swapping。 这可能导致持续 **分钟** 而不是毫秒的垃圾回收，
并可能导致节点响应缓慢甚至集群连接断开。在弹性分布式系统中，这很容易让操作系统杀死节点。

有三种方法禁用 swapping。 首选是完全禁用交换。如果这不是一种选择，选择最小化 swappiness 还是内存锁定取决于你的环境。

[[disable-swap-files]]
==== 禁用所有文件交换

通常 Elasticsearch 是机器上运行的唯一服务，它的内存使用情况由 JVM 选项控制。应该不需要启用交换。

在 Linux 系统，你可以运行以下命令临时禁用交换：

[source,sh]
--------------
sudo swapoff -a
--------------

如果需要永久禁用，你需要编辑 `/etc/fstab` 文件并注释任何包含 `swap` 的行。

在 Windows，可通过 `System Properties → Advanced → Performance → Advanced → Virtual memory` 禁用页文件来实现相同功能。

[[swappiness]]
==== 配置 `swappiness`

Linux 系统上另一个可选项是确保 sysctl `vm.swappiness` 值设为 `1` 。这减少了内核的交换趋势，并在正常情况下不会导致交换，
但是仍然允许整个系统在紧急情况下进行 swapping。

[[bootstrap-memory_lock]]
==== 启用 `bootstrap.memory_lock`

另一个选择是在 Linux/Unix 系统使用 http://opengroup.org/onlinepubs/007908799/xsh/mlockall.html[mlockall]
或在 Windows 使用 https://msdn.microsoft.com/en-us/library/windows/desktop/aa366895%28v=vs.85%29.aspx[VirtualLock]
尝试将进程地址空间锁定到 RAM 中，防止任何 Elasticsearch 内存被换出。 这可以通过在 `config/elasticsearch.yml` 文件添加以下行完成：

[source,yaml]
--------------
bootstrap.memory_lock: true
--------------

WARNING: `mlockall` 如果试图分配比可用内存更多的内存可能会导致 JVM 或 shell 会话退出。

启动 Elasticsearch 后，你可通过检查以下请求输出中的 `mlockall` 值验证这个设置是否应用成功：

[source,js]
--------------
GET _nodes?filter_path=**.mlockall
--------------
// CONSOLE

如果你发现 `mlockall` 是 `false` ，那这意味着 `mlockall` 请求失败。你同样可在日志看到 `Unable to lock JVM Memory` 的更多信息。

Linux/Unix 系统最可能的原因是运行 Elasticsearch 的用户没有锁定内存的权限。可用以下方式授权：

`.zip` 和 `.tar.gz`::

  以 root启动 Elasticsearch 并设置 <<ulimit,`ulimit -l unlimited`>> ，或在 <<limits.conf,`/etc/security/limits.conf`>> 文件设置 `memlock` 为 `unlimited` 。

RPM 和 Debian::

  在 <<sysconfig,系统配置文件>> （使用 `systemd` 的系统参考下文）设置 `MAX_LOCKED_MEMORY` 为 `unlimited` 。

使用 `systemd` 系统::

  在 <<systemd,systemd 配置>> 设置 `LimitMEMLOCK` 为 `infinity` 。

另一个 `mlockall` 失败的原因可能是临时目录（一般是 `/tmp` ）使用 `noexec` 选项加载。
这可通过给 `ES_JAVA_OPTS` 环境变量指定一个新的目录解决。

[source,sh]
--------------
export ES_JAVA_OPTS="$ES_JAVA_OPTS -Djava.io.tmpdir=/path/to/temp/dir"
./bin/elasticsearch
--------------

或在 jvm.options 配置文件内设置这个 JVM 标志。
